package in.nirman.modules.expense.api.dto;

import in.nirman.common.CostAllocation;
import in.nirman.modules.approval.api.dto.ApprovalDtos.ActionRequest;
import in.nirman.modules.expense.domain.Expense;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/** Request and response shapes for expenses and their evidence. */
public final class ExpenseDtos {

    private ExpenseDtos() {
    }

    /**
     * {@code id} is generated by the client so an expense photographed and typed at site
     * with no signal, then synced three times, is one expense.
     *
     * <p>The amount is entered before tax with a rate beside it, never as a total: the two
     * are on the bill separately and deriving one from the others is what stops them
     * disagreeing.</p>
     */
    public record CreateExpenseRequest(
            @NotNull UUID id,
            @NotNull UUID siteId,
            @NotNull LocalDate expenseDate,
            @NotNull UUID categoryId,
            UUID subcategoryId,
            UUID vendorId,
            UUID boqItemId,
            @NotBlank String description,
            @Size(max = 60) String billNumber,
            LocalDate billDate,
            @NotNull @DecimalMin("0") BigDecimal amountBeforeTax,
            @DecimalMin("0") @DecimalMax("100") BigDecimal gstPercent,
            @Size(max = 20) String paymentMode,
            String noBillReason,
            /** Set when this expense is being paid out of a site float. */
            UUID siteAdvanceId,
            String remarks,
            /** Required when re-sending with {@code force=true} after a duplicate warning. */
            String duplicateOverrideReason) {
    }

    public record UpdateExpenseRequest(
            @NotNull LocalDate expenseDate,
            @NotNull UUID categoryId,
            UUID subcategoryId,
            UUID vendorId,
            UUID boqItemId,
            @NotBlank String description,
            @Size(max = 60) String billNumber,
            LocalDate billDate,
            @NotNull @DecimalMin("0") BigDecimal amountBeforeTax,
            @DecimalMin("0") @DecimalMax("100") BigDecimal gstPercent,
            @Size(max = 20) String paymentMode,
            String noBillReason,
            String remarks,
            @NotNull Long version) {
    }

    /**
     * Whose cost it is, decided by the approver or re-decided by the office.
     *
     * @param siteShare the site's part, for {@code SPLIT} and nothing else. Strictly between
     *                  zero and the total: a split giving the site all of it is {@code SITE}
     *                  and one giving it none is {@code COMPANY}.
     * @param note      why, for the bill where the answer is not the obvious one. Optional,
     *                  because demanding a sentence on every office bill produces a column of
     *                  the word "office".
     */
    public record AllocateExpenseRequest(
            @NotNull CostAllocation allocation,
            @DecimalMin("0") BigDecimal siteShare,
            @Size(max = 500) String note) {
    }

    /**
     * The decision, with whose cost it is attached.
     *
     * <p>One call rather than two. Approving the money and saying whose money it was are the
     * same act by the same person at the same moment, and splitting them across two requests
     * leaves a window in which an approved expense has been charged to nobody — and a second
     * screen for the approver who forgot to come back.</p>
     *
     * @param allocation absent leaves the head's own default standing, which is what the
     *                   approver was shown and what he agreed with by not changing it
     */
    public record DecideExpenseRequest(
            @NotNull ActionRequest.Action action,
            @Size(max = 2000) String remarks,
            CostAllocation allocation,
            @DecimalMin("0") BigDecimal siteShare,
            @Size(max = 500) String allocationNote) {
    }

    /**
     * Re-opening an approved expense so its author can correct it.
     *
     * <p>Carries the whole expense rather than a patch, because it is the same form the
     * author typed it in and a half-sent correction is how a bill ends up with last week's
     * amount and this week's date.</p>
     */
    public record ReviseExpenseRequest(
            @NotNull LocalDate expenseDate,
            @NotNull UUID categoryId,
            UUID subcategoryId,
            UUID vendorId,
            UUID boqItemId,
            @NotBlank String description,
            @Size(max = 60) String billNumber,
            LocalDate billDate,
            @NotNull @DecimalMin("0") BigDecimal amountBeforeTax,
            @DecimalMin("0") @DecimalMax("100") BigDecimal gstPercent,
            @Size(max = 20) String paymentMode,
            String noBillReason,
            String remarks,
            /** What was wrong with the figure somebody had already approved. */
            @NotBlank @Size(max = 2000) String reason,
            @NotNull Long version) {
    }

    /**
     * What the register's current filter adds up to, split the way the screen is.
     *
     * <p>Computed per call from the rows themselves — a stored total is a second version of
     * the truth, and this one would go stale the first time the office re-allocated a bill.</p>
     */
    public record AllocationSummary(
            BigDecimal totalBooked,
            BigDecimal siteCost,
            BigDecimal companyCost,
            BigDecimal paid,
            BigDecimal payable,
            int expenseCount,
            int awaitingApproval,
            int unallocatedCount) {
    }

    /**
     * A candidate the new expense looks like a copy of, with the reason it was flagged, so
     * the person deciding can tell a genuine second delivery from a double entry without
     * hunting through a month of paper.
     */
    public record DuplicateCandidate(
            UUID id,
            String expenseNumber,
            LocalDate expenseDate,
            String description,
            String billNumber,
            BigDecimal totalAmount,
            Expense.Workflow workflowStatus,
            String matchedOn) {
    }

    /** The 409 body. Re-send with {@code ?force=true} and a stated reason to book it anyway. */
    public record DuplicateExpenseResponse(
            String detail,
            List<DuplicateCandidate> candidates) {
    }

    public record AttachBillRequest(
            @NotNull UUID attachmentId,
            @Size(max = 30) String docType) {
    }

    public record VoidExpenseRequest(
            @NotBlank @Size(max = 2000) String reason) {
    }

    public record ExpenseAttachmentResponse(
            UUID id,
            UUID attachmentId,
            String docType,
            String fileName,
            String contentType,
            long sizeBytes) {
    }

    public record ExpenseResponse(
            UUID id,
            String expenseNumber,
            UUID siteId,
            UUID projectId,
            LocalDate expenseDate,
            UUID categoryId,
            String categoryName,
            UUID subcategoryId,
            UUID vendorId,
            String vendorName,
            UUID boqItemId,
            String description,
            String billNumber,
            LocalDate billDate,
            BigDecimal amountBeforeTax,
            BigDecimal gstPercent,
            BigDecimal gstAmount,
            BigDecimal totalAmount,
            String paymentMode,
            Expense.PaymentStatus paymentStatus,
            BigDecimal paidAmount,
            /** Approved cost less cash paid. The third amount, never merged with the others. */
            BigDecimal payableAmount,
            String noBillReason,
            UUID siteAdvanceId,
            /** Whose cost it is. The label the register groups by. */
            CostAllocation costAllocation,
            /** What the site's project carries — the total, zero, or the split's site part. */
            BigDecimal siteCost,
            /** Overhead. Derived from the two above, never stored beside them. */
            BigDecimal companyCost,
            String allocationNote,
            /** Null on a row nobody has decided yet: it is carrying its head's proposal. */
            Instant allocatedAt,
            /** How many times the author has re-opened it after approval. Zero for most. */
            int revision,
            Instant revisedAt,
            String revisionReason,
            Expense.Workflow workflowStatus,
            /** Which level is waiting, and on whom. Null once the record is through. */
            Integer pendingLevel,
            String pendingWithRole,
            Instant submittedAt,
            Instant approvedAt,
            String rejectionReason,
            UUID duplicateOfId,
            String remarks,
            Long version,
            List<ExpenseAttachmentResponse> attachments) {
    }
}
