package in.nirman.modules.expense.api.dto;

import in.nirman.modules.expense.domain.Expense;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/** Request and response shapes for expenses and their evidence. */
public final class ExpenseDtos {

    private ExpenseDtos() {
    }

    /**
     * {@code id} is generated by the client so an expense photographed and typed at site
     * with no signal, then synced three times, is one expense.
     *
     * <p>The amount is entered before tax with a rate beside it, never as a total: the two
     * are on the bill separately and deriving one from the others is what stops them
     * disagreeing.</p>
     */
    public record CreateExpenseRequest(
            @NotNull UUID id,
            @NotNull UUID siteId,
            @NotNull LocalDate expenseDate,
            @NotNull UUID categoryId,
            UUID subcategoryId,
            UUID vendorId,
            UUID boqItemId,
            @NotBlank String description,
            @Size(max = 60) String billNumber,
            LocalDate billDate,
            @NotNull @DecimalMin("0") BigDecimal amountBeforeTax,
            @DecimalMin("0") @DecimalMax("100") BigDecimal gstPercent,
            @Size(max = 20) String paymentMode,
            String noBillReason,
            /** Set when this expense is being paid out of a site float. */
            UUID siteAdvanceId,
            String remarks,
            /** Required when re-sending with {@code force=true} after a duplicate warning. */
            String duplicateOverrideReason) {
    }

    public record UpdateExpenseRequest(
            @NotNull LocalDate expenseDate,
            @NotNull UUID categoryId,
            UUID subcategoryId,
            UUID vendorId,
            UUID boqItemId,
            @NotBlank String description,
            @Size(max = 60) String billNumber,
            LocalDate billDate,
            @NotNull @DecimalMin("0") BigDecimal amountBeforeTax,
            @DecimalMin("0") @DecimalMax("100") BigDecimal gstPercent,
            @Size(max = 20) String paymentMode,
            String noBillReason,
            String remarks,
            @NotNull Long version) {
    }

    /**
     * A candidate the new expense looks like a copy of, with the reason it was flagged, so
     * the person deciding can tell a genuine second delivery from a double entry without
     * hunting through a month of paper.
     */
    public record DuplicateCandidate(
            UUID id,
            String expenseNumber,
            LocalDate expenseDate,
            String description,
            String billNumber,
            BigDecimal totalAmount,
            Expense.Workflow workflowStatus,
            String matchedOn) {
    }

    /** The 409 body. Re-send with {@code ?force=true} and a stated reason to book it anyway. */
    public record DuplicateExpenseResponse(
            String detail,
            List<DuplicateCandidate> candidates) {
    }

    public record AttachBillRequest(
            @NotNull UUID attachmentId,
            @Size(max = 30) String docType) {
    }

    public record VoidExpenseRequest(
            @NotBlank @Size(max = 2000) String reason) {
    }

    public record ExpenseAttachmentResponse(
            UUID id,
            UUID attachmentId,
            String docType,
            String fileName,
            String contentType,
            long sizeBytes) {
    }

    public record ExpenseResponse(
            UUID id,
            String expenseNumber,
            UUID siteId,
            UUID projectId,
            LocalDate expenseDate,
            UUID categoryId,
            String categoryName,
            UUID subcategoryId,
            UUID vendorId,
            String vendorName,
            UUID boqItemId,
            String description,
            String billNumber,
            LocalDate billDate,
            BigDecimal amountBeforeTax,
            BigDecimal gstPercent,
            BigDecimal gstAmount,
            BigDecimal totalAmount,
            String paymentMode,
            Expense.PaymentStatus paymentStatus,
            BigDecimal paidAmount,
            /** Approved cost less cash paid. The third amount, never merged with the others. */
            BigDecimal payableAmount,
            String noBillReason,
            UUID siteAdvanceId,
            Expense.Workflow workflowStatus,
            /** Which level is waiting, and on whom. Null once the record is through. */
            Integer pendingLevel,
            String pendingWithRole,
            Instant submittedAt,
            Instant approvedAt,
            String rejectionReason,
            UUID duplicateOfId,
            String remarks,
            Long version,
            List<ExpenseAttachmentResponse> attachments) {
    }
}
