package in.nirman.modules.inventory.api.dto;

import in.nirman.modules.inventory.domain.DocumentWorkflow;
import in.nirman.modules.inventory.domain.StockCorrectionRequest;
import in.nirman.modules.inventory.domain.StockTransaction.SourceType;
import in.nirman.modules.inventory.domain.StockTransaction.TxnType;
import in.nirman.modules.inventory.domain.StockTransfer;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/** Request and response shapes for every inventory document and read. */
public final class InventoryDtos {

    private InventoryDtos() {
    }

    // ------------------------------------------------------------------ goods receipt

    /**
     * One material on a delivery. {@code unitId} is what the challan says — quintals,
     * tonnes, bags — and the server converts it to the material's base unit. The client
     * never sends base quantities, because the challan never has them.
     */
    /**
     * {@code rate} is optional and normally absent. The storekeeper books what came off the
     * lorry against a challan that often carries no price at all; the office prices the line
     * against the invoice afterwards, and the service refuses a rate from anyone who does
     * not hold {@code inventory:price} rather than quietly dropping it.
     */
    public record ReceiptLine(
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @DecimalMin("0") BigDecimal rate,
            @DecimalMin("0") BigDecimal gstPercent,
            @Size(max = 300) String remarks) {
    }

    /**
     * {@code id} is generated by the client so a delivery booked at the gate with no signal
     * and synced three times is one delivery.
     */
    public record CreateReceiptRequest(
            @NotNull UUID id,
            @NotNull UUID storeId,
            @NotNull LocalDate receiptDate,
            UUID vendorId,
            UUID poId,
            @Size(max = 60) String invoiceNumber,
            LocalDate invoiceDate,
            @Size(max = 60) String challanNumber,
            @Size(max = 25) String vehicleNumber,
            String remarks,
            /**
             * What came off the lorry. A picture, and the server means it: nothing but a
             * camera can say what arrived, and the load is gone by the time anybody asks.
             */
            UUID materialPhotoId,
            /**
             * The invoice or challan that came with it — what the supplier claims he sent,
             * which is a different claim from what arrived. May be a PDF: half the suppliers
             * who send one at all send it that way.
             */
            UUID invoicePhotoId,
            @NotEmpty @Valid List<ReceiptLine> lines) {
    }

    /** One picture on a movement of stock, and what it is a picture of. */
    public record MovementPhoto(UUID attachmentId, String docType) {
    }

    public record ReceiptLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            UUID unitId,
            String unitCode,
            BigDecimal quantity,
            BigDecimal quantityBase,
            String baseUnitCode,
            BigDecimal rate,
            BigDecimal rateBase,
            BigDecimal gstPercent,
            BigDecimal gstAmount,
            BigDecimal amount,
            String remarks) {
    }

    public record ReceiptResponse(
            UUID id,
            String grnNumber,
            UUID siteId,
            UUID storeId,
            String storeName,
            UUID vendorId,
            LocalDate receiptDate,
            String invoiceNumber,
            LocalDate invoiceDate,
            String challanNumber,
            String vehicleNumber,
            BigDecimal subTotal,
            BigDecimal gstAmount,
            BigDecimal totalAmount,
            DocumentWorkflow workflowStatus,
            Instant verifiedAt,
            String rejectionReason,
            String remarks,
            Long version,
            List<ReceiptLineResponse> lines,
            /** The load and the paper. Evidence nobody can look at is a row saying evidence exists. */
            List<MovementPhoto> photos) {
    }

    /**
     * The 409 body when the same vendor invoice is already on file. Carries the receipts it
     * clashed with, because "duplicate" without saying which one sends a storekeeper hunting
     * through a month of paper.
     */
    public record DuplicateReceiptResponse(
            String invoiceNumber,
            List<ReceiptResponse> candidates) {
    }

    // ------------------------------------------------------------------ issue

    public record IssueLine(
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            /** Overrides the header's BOQ item when one slip covers two work items. */
            UUID boqItemId,
            @Size(max = 300) String remarks) {
    }

    /**
     * Either {@code boqItemId} or {@code purpose} must be present — material that left the
     * store and can be charged to nothing is how consumption stops being answerable. The
     * service enforces it; it is not expressible as a field annotation.
     */
    public record CreateIssueRequest(
            @NotNull UUID id,
            @NotNull UUID storeId,
            @NotNull LocalDate issueDate,
            UUID boqItemId,
            @Size(max = 300) String purpose,
            @Size(max = 150) String issuedToName,
            UUID issuedToSupplierId,
            @Size(max = 150) String workLocation,
            /** What went out. One picture; there is no third party on an issue and no paper. */
            UUID materialPhotoId,
            @NotEmpty @Valid List<IssueLine> lines) {
    }

    public record IssueLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            UUID unitId,
            String unitCode,
            BigDecimal quantity,
            BigDecimal quantityBase,
            String baseUnitCode,
            /** The moving average frozen when the stock left. Null until the issue is approved. */
            BigDecimal issuedRate,
            BigDecimal value,
            UUID boqItemId,
            String remarks) {
    }

    public record IssueResponse(
            UUID id,
            String issueNumber,
            UUID siteId,
            UUID storeId,
            String storeName,
            LocalDate issueDate,
            String issuedToName,
            UUID issuedToSupplierId,
            UUID boqItemId,
            String workLocation,
            String purpose,
            DocumentWorkflow workflowStatus,
            Instant approvedAt,
            String rejectionReason,
            BigDecimal totalValue,
            Long version,
            List<IssueLineResponse> lines,
            /** What went out, as a picture. */
            List<MovementPhoto> photos) {
    }

    // ------------------------------------------------------------------ transfer

    public record TransferLine(
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @Size(max = 300) String remarks) {
    }

    public record CreateTransferRequest(
            @NotNull UUID id,
            @NotNull UUID fromStoreId,
            @NotNull UUID toStoreId,
            @NotNull LocalDate transferDate,
            @Size(max = 25) String vehicleNumber,
            String remarks,
            @NotEmpty @Valid List<TransferLine> lines) {
    }

    /** What actually arrived. An absent quantity means all of it did — the common case. */
    public record ReceiveTransferLine(
            @NotNull UUID lineId,
            @DecimalMin("0") BigDecimal receivedQuantityBase,
            @Size(max = 300) String remarks) {
    }

    public record ReceiveTransferRequest(
            @Valid List<ReceiveTransferLine> lines,
            @Size(max = 500) String remarks) {
    }

    public record TransferLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            UUID unitId,
            String unitCode,
            BigDecimal quantity,
            BigDecimal quantityBase,
            String baseUnitCode,
            BigDecimal receivedQtyBase,
            BigDecimal shortageQtyBase,
            BigDecimal rateBase,
            String remarks) {
    }

    public record TransferResponse(
            UUID id,
            String transferNumber,
            UUID fromStoreId,
            String fromStoreName,
            UUID toStoreId,
            String toStoreName,
            LocalDate transferDate,
            String vehicleNumber,
            StockTransfer.Status status,
            Instant dispatchedAt,
            Instant receivedAt,
            String remarks,
            Long version,
            List<TransferLineResponse> lines) {
    }

    // ------------------------------------------------------------------ opening, wastage, adjustment

    /** One-time per store and material. The server refuses a second one. */
    public record OpeningStockRequest(
            @NotNull UUID storeId,
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @NotNull @DecimalMin("0") BigDecimal rate,
            @NotNull LocalDate asOfDate,
            @Size(max = 500) String remarks) {
    }

    public record WastageRequest(
            @NotNull UUID storeId,
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @NotNull LocalDate wastageDate,
            @NotNull Type type,
            /** Mandatory. Stock leaving without a sale or an issue has to explain itself. */
            @NotBlank @Size(max = 500) String reason,
            UUID boqItemId) {

        public enum Type { WASTAGE, DAMAGE }
    }

    public record AdjustmentRequest(
            @NotNull UUID storeId,
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            /** Signed: negative writes stock off, positive writes it on. */
            @NotNull BigDecimal quantityDelta,
            @NotNull LocalDate adjustmentDate,
            @NotBlank @Size(max = 500) String reason) {
    }

    // ------------------------------------------------------------------ physical count

    public record CountLine(
            @NotNull UUID materialId,
            @NotNull @DecimalMin("0") BigDecimal countedQuantityBase,
            @Size(max = 300) String varianceReason) {
    }

    public record CreateCountRequest(
            @NotNull UUID storeId,
            @NotNull LocalDate countDate,
            @Size(max = 500) String remarks,
            @NotEmpty @Valid List<CountLine> lines) {
    }

    public record DecideCountRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { APPROVE, REJECT }
    }

    public record CountLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            String baseUnitCode,
            BigDecimal systemQtyBase,
            BigDecimal countedQtyBase,
            BigDecimal varianceQtyBase,
            String varianceReason) {
    }

    public record CountResponse(
            UUID id,
            String countNumber,
            UUID storeId,
            String storeName,
            LocalDate countDate,
            DocumentWorkflow status,
            Instant approvedAt,
            String remarks,
            Long version,
            List<CountLineResponse> lines) {
    }

    // ------------------------------------------------------------------ decisions

    public record VerifyReceiptRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { VERIFY, REJECT }
    }

    /**
     * What the office says a delivery cost, line by line.
     *
     * <p>Its own call rather than a field on the verify request, because pricing and
     * checking against the challan are two acts and only sometimes the same person's. An
     * accountant may price a week of receipts without deciding whether any of them matched
     * what turned up; the engineer standing at the store may do both in one go, and the
     * screen makes that two requests rather than making this one mean two things.</p>
     *
     * <p>Lines omitted keep the rate they had, so correcting one line of eight is a request
     * about one line.</p>
     */
    public record PriceReceiptRequest(
            @NotEmpty @Valid List<LinePrice> lines) {
    }

    public record LinePrice(
            @NotNull UUID lineId,
            /** Per the line's own unit, excluding tax. Zero is allowed: free issue happens. */
            @NotNull @DecimalMin("0") BigDecimal rate,
            @DecimalMin("0") BigDecimal gstPercent) {
    }

    public record ApproveIssueRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { APPROVE, REJECT }
    }

    // ------------------------------------------------------------------ reads

    /** One line of the stock position: what a store holds, at what average, worth what. */
    public record StockRow(
            UUID storeId,
            String storeCode,
            String storeName,
            UUID siteId,
            UUID materialId,
            String materialCode,
            String materialName,
            String baseUnitCode,
            BigDecimal quantityBase,
            BigDecimal movingAvgRate,
            BigDecimal stockValue,
            BigDecimal inTransitQtyBase,
            BigDecimal minStockLevel,
            /** Below the material's own reorder level. Per material, not one number per store. */
            boolean low,
            Instant lastTxnAt) {
    }

    public record StockPosition(
            List<StockRow> rows,
            BigDecimal totalValue) {
    }

    /** One movement, as the ledger screen shows it. */
    public record LedgerRow(
            UUID id,
            LocalDate txnDate,
            UUID storeId,
            String storeName,
            UUID materialId,
            String materialCode,
            String materialName,
            String baseUnitCode,
            TxnType txnType,
            short direction,
            BigDecimal quantityBase,
            BigDecimal rateBase,
            BigDecimal value,
            BigDecimal balanceAfter,
            BigDecimal avgRateAfter,
            SourceType sourceType,
            UUID sourceId,
            UUID boqItemId,
            String reason,
            Instant createdAt) {
    }

    // ------------------------------------------------------------------ stock corrections

    /**
     * The field asking for a stock figure to be put right.
     *
     * <p>Signed like {@link AdjustmentRequest}, and for the same reason: a shed can hold less
     * than the ledger says or more, and a screen that only allowed one direction would teach
     * the storekeeper to report half of what he finds.</p>
     *
     * <p>The reason is required. A movement with nothing behind it is indistinguishable from
     * stock walking out of the gate, and this one is being asked for by the person best
     * placed to make that unreadable.</p>
     */
    public record StockCorrectionRequestBody(
            @NotNull UUID id,
            @NotNull UUID storeId,
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull BigDecimal quantityDelta,
            @NotNull LocalDate correctionDate,
            @NotBlank @Size(max = 500) String reason) {
    }

    /** Accepting posts the adjustment; refusing posts nothing and keeps the row. */
    public record DecideStockCorrectionRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action {
            ACCEPT,
            REJECT
        }
    }

    public record StockCorrectionResponse(
            UUID id,
            UUID siteId,
            UUID storeId,
            String storeName,
            UUID materialId,
            String materialName,
            UUID unitId,
            String unitCode,
            BigDecimal quantityDelta,
            LocalDate correctionDate,
            String reason,
            StockCorrectionRequest.Status status,
            UUID postedTxnId,
            Instant decidedAt,
            String decisionRemarks,
            Instant createdAt,
            UUID createdBy,
            Long version) {
    }
}
