package in.nirman.modules.inventory.api.dto;

import in.nirman.modules.inventory.domain.DocumentWorkflow;
import in.nirman.modules.inventory.domain.StockTransaction.SourceType;
import in.nirman.modules.inventory.domain.StockTransaction.TxnType;
import in.nirman.modules.inventory.domain.StockTransfer;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/** Request and response shapes for every inventory document and read. */
public final class InventoryDtos {

    private InventoryDtos() {
    }

    // ------------------------------------------------------------------ goods receipt

    /**
     * One material on a delivery. {@code unitId} is what the challan says — quintals,
     * tonnes, bags — and the server converts it to the material's base unit. The client
     * never sends base quantities, because the challan never has them.
     */
    public record ReceiptLine(
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @NotNull @DecimalMin("0") BigDecimal rate,
            @DecimalMin("0") BigDecimal gstPercent,
            @Size(max = 300) String remarks) {
    }

    /**
     * {@code id} is generated by the client so a delivery booked at the gate with no signal
     * and synced three times is one delivery.
     */
    public record CreateReceiptRequest(
            @NotNull UUID id,
            @NotNull UUID storeId,
            @NotNull LocalDate receiptDate,
            UUID vendorId,
            UUID poId,
            @Size(max = 60) String invoiceNumber,
            LocalDate invoiceDate,
            @Size(max = 60) String challanNumber,
            @Size(max = 25) String vehicleNumber,
            String remarks,
            @NotEmpty @Valid List<ReceiptLine> lines) {
    }

    public record ReceiptLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            UUID unitId,
            String unitCode,
            BigDecimal quantity,
            BigDecimal quantityBase,
            String baseUnitCode,
            BigDecimal rate,
            BigDecimal rateBase,
            BigDecimal gstPercent,
            BigDecimal gstAmount,
            BigDecimal amount,
            String remarks) {
    }

    public record ReceiptResponse(
            UUID id,
            String grnNumber,
            UUID siteId,
            UUID storeId,
            String storeName,
            UUID vendorId,
            LocalDate receiptDate,
            String invoiceNumber,
            LocalDate invoiceDate,
            String challanNumber,
            String vehicleNumber,
            BigDecimal subTotal,
            BigDecimal gstAmount,
            BigDecimal totalAmount,
            DocumentWorkflow workflowStatus,
            Instant verifiedAt,
            String rejectionReason,
            String remarks,
            Long version,
            List<ReceiptLineResponse> lines) {
    }

    /**
     * The 409 body when the same vendor invoice is already on file. Carries the receipts it
     * clashed with, because "duplicate" without saying which one sends a storekeeper hunting
     * through a month of paper.
     */
    public record DuplicateReceiptResponse(
            String invoiceNumber,
            List<ReceiptResponse> candidates) {
    }

    // ------------------------------------------------------------------ issue

    public record IssueLine(
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            /** Overrides the header's BOQ item when one slip covers two work items. */
            UUID boqItemId,
            @Size(max = 300) String remarks) {
    }

    /**
     * Either {@code boqItemId} or {@code purpose} must be present — material that left the
     * store and can be charged to nothing is how consumption stops being answerable. The
     * service enforces it; it is not expressible as a field annotation.
     */
    public record CreateIssueRequest(
            @NotNull UUID id,
            @NotNull UUID storeId,
            @NotNull LocalDate issueDate,
            UUID boqItemId,
            @Size(max = 300) String purpose,
            @Size(max = 150) String issuedToName,
            UUID issuedToContractorId,
            @Size(max = 150) String workLocation,
            @NotEmpty @Valid List<IssueLine> lines) {
    }

    public record IssueLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            UUID unitId,
            String unitCode,
            BigDecimal quantity,
            BigDecimal quantityBase,
            String baseUnitCode,
            /** The moving average frozen when the stock left. Null until the issue is approved. */
            BigDecimal issuedRate,
            BigDecimal value,
            UUID boqItemId,
            String remarks) {
    }

    public record IssueResponse(
            UUID id,
            String issueNumber,
            UUID siteId,
            UUID storeId,
            String storeName,
            LocalDate issueDate,
            String issuedToName,
            UUID issuedToContractorId,
            UUID boqItemId,
            String workLocation,
            String purpose,
            DocumentWorkflow workflowStatus,
            Instant approvedAt,
            String rejectionReason,
            BigDecimal totalValue,
            Long version,
            List<IssueLineResponse> lines) {
    }

    // ------------------------------------------------------------------ transfer

    public record TransferLine(
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @Size(max = 300) String remarks) {
    }

    public record CreateTransferRequest(
            @NotNull UUID id,
            @NotNull UUID fromStoreId,
            @NotNull UUID toStoreId,
            @NotNull LocalDate transferDate,
            @Size(max = 25) String vehicleNumber,
            String remarks,
            @NotEmpty @Valid List<TransferLine> lines) {
    }

    /** What actually arrived. An absent quantity means all of it did — the common case. */
    public record ReceiveTransferLine(
            @NotNull UUID lineId,
            @DecimalMin("0") BigDecimal receivedQuantityBase,
            @Size(max = 300) String remarks) {
    }

    public record ReceiveTransferRequest(
            @Valid List<ReceiveTransferLine> lines,
            @Size(max = 500) String remarks) {
    }

    public record TransferLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            UUID unitId,
            String unitCode,
            BigDecimal quantity,
            BigDecimal quantityBase,
            String baseUnitCode,
            BigDecimal receivedQtyBase,
            BigDecimal shortageQtyBase,
            BigDecimal rateBase,
            String remarks) {
    }

    public record TransferResponse(
            UUID id,
            String transferNumber,
            UUID fromStoreId,
            String fromStoreName,
            UUID toStoreId,
            String toStoreName,
            LocalDate transferDate,
            String vehicleNumber,
            StockTransfer.Status status,
            Instant dispatchedAt,
            Instant receivedAt,
            String remarks,
            Long version,
            List<TransferLineResponse> lines) {
    }

    // ------------------------------------------------------------------ opening, wastage, adjustment

    /** One-time per store and material. The server refuses a second one. */
    public record OpeningStockRequest(
            @NotNull UUID storeId,
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @NotNull @DecimalMin("0") BigDecimal rate,
            @NotNull LocalDate asOfDate,
            @Size(max = 500) String remarks) {
    }

    public record WastageRequest(
            @NotNull UUID storeId,
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            @NotNull @DecimalMin(value = "0", inclusive = false) BigDecimal quantity,
            @NotNull LocalDate wastageDate,
            @NotNull Type type,
            /** Mandatory. Stock leaving without a sale or an issue has to explain itself. */
            @NotBlank @Size(max = 500) String reason,
            UUID boqItemId) {

        public enum Type { WASTAGE, DAMAGE }
    }

    public record AdjustmentRequest(
            @NotNull UUID storeId,
            @NotNull UUID materialId,
            @NotNull UUID unitId,
            /** Signed: negative writes stock off, positive writes it on. */
            @NotNull BigDecimal quantityDelta,
            @NotNull LocalDate adjustmentDate,
            @NotBlank @Size(max = 500) String reason) {
    }

    // ------------------------------------------------------------------ physical count

    public record CountLine(
            @NotNull UUID materialId,
            @NotNull @DecimalMin("0") BigDecimal countedQuantityBase,
            @Size(max = 300) String varianceReason) {
    }

    public record CreateCountRequest(
            @NotNull UUID storeId,
            @NotNull LocalDate countDate,
            @Size(max = 500) String remarks,
            @NotEmpty @Valid List<CountLine> lines) {
    }

    public record DecideCountRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { APPROVE, REJECT }
    }

    public record CountLineResponse(
            UUID id,
            UUID materialId,
            String materialCode,
            String materialName,
            String baseUnitCode,
            BigDecimal systemQtyBase,
            BigDecimal countedQtyBase,
            BigDecimal varianceQtyBase,
            String varianceReason) {
    }

    public record CountResponse(
            UUID id,
            String countNumber,
            UUID storeId,
            String storeName,
            LocalDate countDate,
            DocumentWorkflow status,
            Instant approvedAt,
            String remarks,
            Long version,
            List<CountLineResponse> lines) {
    }

    // ------------------------------------------------------------------ decisions

    public record VerifyReceiptRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { VERIFY, REJECT }
    }

    public record ApproveIssueRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { APPROVE, REJECT }
    }

    // ------------------------------------------------------------------ reads

    /** One line of the stock position: what a store holds, at what average, worth what. */
    public record StockRow(
            UUID storeId,
            String storeCode,
            String storeName,
            UUID siteId,
            UUID materialId,
            String materialCode,
            String materialName,
            String baseUnitCode,
            BigDecimal quantityBase,
            BigDecimal movingAvgRate,
            BigDecimal stockValue,
            BigDecimal inTransitQtyBase,
            BigDecimal minStockLevel,
            /** Below the material's own reorder level. Per material, not one number per store. */
            boolean low,
            Instant lastTxnAt) {
    }

    public record StockPosition(
            List<StockRow> rows,
            BigDecimal totalValue) {
    }

    /** One movement, as the ledger screen shows it. */
    public record LedgerRow(
            UUID id,
            LocalDate txnDate,
            UUID storeId,
            String storeName,
            UUID materialId,
            String materialCode,
            String materialName,
            String baseUnitCode,
            TxnType txnType,
            short direction,
            BigDecimal quantityBase,
            BigDecimal rateBase,
            BigDecimal value,
            BigDecimal balanceAfter,
            BigDecimal avgRateAfter,
            SourceType sourceType,
            UUID sourceId,
            UUID boqItemId,
            String reason,
            Instant createdAt) {
    }
}
