package in.nirman.modules.tender.domain;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;

import java.util.Arrays;
import java.util.List;

/**
 * Stores the parser's warnings as one text column, a warning per line.
 *
 * <p>A child table would mean three joins for a list that is only ever read whole, alongside
 * the document it belongs to. Newline-delimited text is honest about that: the warnings are a
 * note attached to the reading, not queryable data.</p>
 */
@Converter
public class WarningListConverter implements AttributeConverter<List<String>, String> {

    @Override
    public String convertToDatabaseColumn(List<String> warnings) {
        if (warnings == null || warnings.isEmpty()) {
            return null;
        }
        // A warning is a single sentence generated by this codebase, so it cannot itself
        // contain a newline and the delimiter is unambiguous.
        return String.join("\n", warnings);
    }

    @Override
    public List<String> convertToEntityAttribute(String column) {
        if (column == null || column.isBlank()) {
            return List.of();
        }
        return Arrays.stream(column.split("\n")).filter(line -> !line.isBlank()).toList();
    }
}
