package in.nirman.modules.labour.api.dto;

import in.nirman.modules.labour.domain.WorkerAdvance;
import in.nirman.modules.labour.domain.WorkerLedgerEntry;
import in.nirman.modules.labour.domain.WorkerPayment;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/** Worker advances, the wage ledger and the settlement view built on both. */
public final class AdvanceDtos {

    private AdvanceDtos() {
    }

    public record AdvanceResponse(
            UUID id,
            String advanceNumber,
            UUID siteId,
            UUID workerId,
            String workerName,
            LocalDate advanceDate,
            BigDecimal amount,
            WorkerAdvance.PaymentMode paymentMode,
            String purpose,
            boolean recoverable,
            BigDecimal recoveredAmount,
            BigDecimal balanceAmount,
            WorkerAdvance.Status status,
            WorkerAdvance.Workflow workflowStatus,
            Instant approvedAt,
            String remarks,
            Long version) {
    }

    /**
     * {@code id} is generated by the client so an advance handed over on site with no signal
     * syncs exactly once. The advance number is assigned by the server on arrival — a device
     * cannot safely invent one (docs/09).
     */
    public record CreateAdvanceRequest(
            @NotNull UUID id,
            @NotNull UUID siteId,
            @NotNull UUID workerId,
            @NotNull LocalDate advanceDate,
            @NotNull @DecimalMin(value = "0", inclusive = false)
            @Digits(integer = 16, fraction = 2) BigDecimal amount,
            @NotNull WorkerAdvance.PaymentMode paymentMode,
            @Size(max = 300) String purpose,
            /**
             * Whether this comes back out of his wages. Cash usually does; ration, footwear
             * and medicine vary by item and by firm, so it is never assumed.
             */
            boolean recoverable,
            String remarks) {
    }

    public record ApproveAdvanceRequest(
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { APPROVE, REJECT }
    }

    // ------------------------------------------------------------------ ledger and settlement

    public record LedgerEntryResponse(
            UUID id,
            LocalDate entryDate,
            String periodYearMonth,
            WorkerLedgerEntry.EntryType entryType,
            short direction,
            BigDecimal amount,
            BigDecimal balanceAfter,
            WorkerLedgerEntry.SourceType sourceType,
            UUID sourceId,
            String reason) {
    }

    /**
     * What the field sheet computes by hand, per worker per month:
     * {@code Total Amount − Advance = Balance Payment}.
     *
     * <p>{@code openAdvanceAmount} is the part of {@code advanceAmount} no payday has yet
     * closed — what the next one will mark recovered. It is read off the advances, not the
     * ledger, because the ledger netted them the day they were approved and does not know
     * which have since been settled.</p>
     */
    public record SettlementResponse(
            UUID workerId,
            String workerCode,
            String workerName,
            BigDecimal earnedAmount,
            BigDecimal advanceAmount,
            BigDecimal openAdvanceAmount,
            BigDecimal paidAmount,
            BigDecimal deductionAmount,
            BigDecimal netPayable,
            Instant lastEntryAt,
            List<LedgerEntryResponse> entries) {
    }

    // ------------------------------------------------------------------ paydays

    public record PaymentResponse(
            UUID id,
            String paymentNumber,
            UUID siteId,
            UUID workerId,
            String workerName,
            LocalDate paymentDate,
            BigDecimal amount,
            WorkerPayment.PaymentMode paymentMode,
            String referenceNumber,
            /** What this payday closed of his open advances. */
            BigDecimal advancesRecovered,
            String remarks,
            Long version) {
    }

    /**
     * Wages handed over. The id is the client's for the reason the advance's is; the amount
     * may not exceed what the ledger says he is owed — anything beyond that is an advance,
     * and there is a screen for one.
     */
    public record CreatePaymentRequest(
            @NotNull UUID id,
            @NotNull UUID siteId,
            @NotNull UUID workerId,
            @NotNull LocalDate paymentDate,
            @NotNull @DecimalMin(value = "0", inclusive = false)
            @Digits(integer = 16, fraction = 2) BigDecimal amount,
            @NotNull WorkerPayment.PaymentMode paymentMode,
            @Size(max = 100) String referenceNumber,
            @Size(max = 500) String remarks) {
    }
}
