package in.nirman.modules.labour.api.dto;

import in.nirman.modules.labour.domain.AttendanceStatus;
import in.nirman.modules.labour.domain.WorkflowStatus;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

/** Request and response shapes for attendance entry, verification and reporting. */
public final class AttendanceDtos {

    private AttendanceDtos() {
    }

    // ------------------------------------------------------------------ roster

    /**
     * One line of the muster roll. {@code attendance} is null for a worker not yet marked,
     * which is what lets the screen render the whole roster in one pass.
     */
    public record RosterEntry(
            UUID workerId,
            String workerCode,
            String workerName,
            UUID skillCategoryId,
            UUID labourContractorId,
            BigDecimal normalRate,
            BigDecimal overtimeRate,
            AttendanceResponse attendance) {
    }

    public record RosterResponse(
            UUID siteId,
            LocalDate date,
            BigDecimal standardShiftHours,
            /** Above this many overtime hours the entry screen demands a reason. */
            BigDecimal overtimeReasonRequiredAboveHours,
            boolean periodLocked,
            List<RosterEntry> entries) {
    }

    // ------------------------------------------------------------------ entry

    /**
     * One record in a bulk save. {@code id} is generated by the client so the same batch
     * re-sent over a flaky connection creates one row, not three.
     */
    public record AttendanceEntry(
            @NotNull UUID id,
            @NotNull UUID workerId,
            @NotNull AttendanceStatus status,
            LocalTime checkInTime,
            LocalTime checkOutTime,
            @Min(0) @Max(1439) int breakMinutes,
            /**
             * Hours the supervisor typed. Overrides the clock readings when both are sent.
             * Optional so that a client which only knows about times — an offline draft
             * queued before this field existed — keeps working unchanged.
             */
            @DecimalMin("0") @DecimalMax("24") BigDecimal enteredHours,
            @Size(max = 300) String overtimeReason,
            UUID boqItemId,
            @Size(max = 150) String workLocation,
            String remarks) {
    }

    public record BulkAttendanceRequest(
            @NotNull UUID siteId,
            @NotNull LocalDate date,
            @NotEmpty @Valid List<AttendanceEntry> entries) {
    }

    /** Per-entry outcome, so one bad row does not sink an otherwise good batch. */
    public record BulkAttendanceResponse(
            int accepted,
            int unchanged,
            int rejected,
            List<EntryOutcome> outcomes) {

        public record EntryOutcome(UUID id, UUID workerId, Outcome outcome, String reason) {
        }

        public enum Outcome {
            CREATED,
            UPDATED,
            /** Already stored exactly as sent — the idempotent replay case. */
            UNCHANGED,
            REJECTED
        }
    }

    public record UpdateAttendanceRequest(
            @NotNull AttendanceStatus status,
            LocalTime checkInTime,
            LocalTime checkOutTime,
            @Min(0) @Max(1439) int breakMinutes,
            @DecimalMin("0") @DecimalMax("24") BigDecimal enteredHours,
            @Size(max = 300) String overtimeReason,
            UUID boqItemId,
            @Size(max = 150) String workLocation,
            String remarks,
            @NotNull Long version) {
    }

    public record SubmitAttendanceRequest(
            @NotNull UUID siteId,
            @NotNull LocalDate date) {
    }

    /**
     * A change to a row that has already been verified and paid. Carries a reason because
     * the money has moved: somebody will ask why the ledger has an adjustment on it.
     */
    public record CorrectAttendanceRequest(
            @NotNull AttendanceStatus status,
            LocalTime checkInTime,
            LocalTime checkOutTime,
            @Min(0) @Max(1439) int breakMinutes,
            @DecimalMin("0") @DecimalMax("24") BigDecimal enteredHours,
            @Size(max = 300) String overtimeReason,
            UUID boqItemId,
            @Size(max = 150) String workLocation,
            String remarks,
            @NotBlank @Size(max = 2000) String correctionReason,
            @NotNull Long version) {
    }

    public record VerifyAttendanceRequest(
            @NotEmpty List<UUID> ids,
            @NotNull Action action,
            @Size(max = 500) String remarks) {

        public enum Action { VERIFY, REJECT }
    }

    public record LockPeriodRequest(
            @NotNull UUID siteId,
            /** YYYY-MM. */
            @NotNull @jakarta.validation.constraints.Pattern(regexp = "\\d{4}-\\d{2}")
            String yearMonth) {
    }

    // ------------------------------------------------------------------ responses

    public record AttendanceResponse(
            UUID id,
            UUID siteId,
            UUID projectId,
            UUID workerId,
            String workerName,
            LocalDate attendanceDate,
            AttendanceStatus status,
            LocalTime checkInTime,
            LocalTime checkOutTime,
            int breakMinutes,
            /** What the supervisor typed; null when the hours came from the clock instead. */
            BigDecimal enteredHours,
            BigDecimal workedHours,
            BigDecimal regularHours,
            BigDecimal overtimeHours,
            UUID boqItemId,
            String workLocation,
            String overtimeReason,
            String remarks,
            BigDecimal appliedNormalRate,
            BigDecimal appliedOtRate,
            BigDecimal computedWageAmount,
            BigDecimal computedOtAmount,
            BigDecimal totalAmount,
            WorkflowStatus workflowStatus,
            String rejectionReason,
            Long version) {
    }

    /** One row of {@code /attendance/summary}, whatever it was grouped by. */
    public record AttendanceSummaryRow(
            String groupKey,
            String groupLabel,
            long presentDays,
            long halfDays,
            long absentDays,
            long leaveDays,
            BigDecimal regularHours,
            BigDecimal overtimeHours,
            BigDecimal wageAmount,
            BigDecimal overtimeAmount,
            BigDecimal totalAmount) {
    }

    public enum SummaryGroupBy { WORKER, CONTRACTOR, SKILL, DATE }
}
