package in.nirman.modules.labour.domain;

import in.nirman.common.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Cash or goods handed to a worker against wages he has earned or will earn.
 *
 * <p>Distinct from {@code site_advances}, which issues petty cash to a <b>user</b> holding a
 * login. A worker is not a user, and conflating the two would put a labourer's ration money
 * in the same table as a supervisor's imprest float.</p>
 *
 * <p>{@code recoverable} is recorded rather than assumed. The field sheets mix cash with
 * ration, footwear and medicine, and whether each is deducted from the worker or borne by
 * the contractor varies per item — it was the one question the workbooks could not answer,
 * so it is asked per advance (docs/09).</p>
 */
@Entity
@Table(name = "worker_advances")
public class WorkerAdvance extends BaseEntity {

    public enum PaymentMode { CASH, BANK, UPI, CHEQUE, GOODS }

    /** Recovery progress against wages. */
    public enum Status { OPEN, PARTIALLY_RECOVERED, RECOVERED, WRITTEN_OFF }

    public enum Workflow { DRAFT, SUBMITTED, APPROVED, REJECTED, CANCELLED }

    @Column(name = "org_id", nullable = false, updatable = false)
    private UUID orgId;

    @Column(name = "project_id", nullable = false, updatable = false)
    private UUID projectId;

    @Column(name = "site_id", nullable = false, updatable = false)
    private UUID siteId;

    @Column(name = "worker_id", nullable = false, updatable = false)
    private UUID workerId;

    @Column(name = "advance_number", nullable = false, length = 50, updatable = false)
    private String advanceNumber;

    @Column(name = "advance_date", nullable = false, updatable = false)
    private LocalDate advanceDate;

    @Column(name = "amount", nullable = false, precision = 18, scale = 2)
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_mode", nullable = false, length = 20)
    private PaymentMode paymentMode = PaymentMode.CASH;

    @Column(name = "purpose", length = 300)
    private String purpose;

    @Column(name = "is_recoverable", nullable = false)
    private boolean recoverable = true;

    @Column(name = "expense_id")
    private UUID expenseId;

    @Column(name = "recovered_amount", nullable = false, precision = 18, scale = 2)
    private BigDecimal recoveredAmount = BigDecimal.ZERO;

    /** Generated by the database as amount − recovered; never written from Java. */
    @Column(name = "balance_amount", precision = 18, scale = 2,
            insertable = false, updatable = false)
    private BigDecimal balanceAmount;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private Status status = Status.OPEN;

    @Enumerated(EnumType.STRING)
    @Column(name = "workflow_status", nullable = false, length = 20)
    private Workflow workflowStatus = Workflow.DRAFT;

    @Column(name = "approved_by")
    private UUID approvedBy;

    @Column(name = "approved_at")
    private Instant approvedAt;

    @Column(name = "remarks")
    private String remarks;

    @Enumerated(EnumType.STRING)
    @Column(name = "source", nullable = false, length = 15)
    private AttendanceRecord.Source source = AttendanceRecord.Source.ONLINE;

    protected WorkerAdvance() {
    }

    public WorkerAdvance(UUID id, UUID orgId, UUID projectId, UUID siteId, UUID workerId,
                         String advanceNumber, LocalDate advanceDate, BigDecimal amount) {
        setId(id);
        this.orgId = orgId;
        this.projectId = projectId;
        this.siteId = siteId;
        this.workerId = workerId;
        this.advanceNumber = advanceNumber;
        this.advanceDate = advanceDate;
        this.amount = amount;
    }

    public void approve(Instant at, UUID by) {
        this.workflowStatus = Workflow.APPROVED;
        this.approvedAt = at;
        this.approvedBy = by;
    }

    public void reject(Instant at, UUID by, String reason) {
        this.workflowStatus = Workflow.REJECTED;
        this.approvedAt = at;
        this.approvedBy = by;
        this.remarks = reason;
    }

    public boolean isApproved() {
        return workflowStatus == Workflow.APPROVED;
    }

    public UUID getOrgId() {
        return orgId;
    }

    public UUID getProjectId() {
        return projectId;
    }

    public UUID getSiteId() {
        return siteId;
    }

    public UUID getWorkerId() {
        return workerId;
    }

    public String getAdvanceNumber() {
        return advanceNumber;
    }

    public LocalDate getAdvanceDate() {
        return advanceDate;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public PaymentMode getPaymentMode() {
        return paymentMode;
    }

    public void setPaymentMode(PaymentMode paymentMode) {
        this.paymentMode = paymentMode;
    }

    public String getPurpose() {
        return purpose;
    }

    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    public boolean isRecoverable() {
        return recoverable;
    }

    public void setRecoverable(boolean recoverable) {
        this.recoverable = recoverable;
    }

    public UUID getExpenseId() {
        return expenseId;
    }

    public BigDecimal getRecoveredAmount() {
        return recoveredAmount;
    }

    public BigDecimal getBalanceAmount() {
        return balanceAmount;
    }

    public Status getStatus() {
        return status;
    }

    public Workflow getWorkflowStatus() {
        return workflowStatus;
    }

    public UUID getApprovedBy() {
        return approvedBy;
    }

    public Instant getApprovedAt() {
        return approvedAt;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public void setSource(AttendanceRecord.Source source) {
        this.source = source;
    }
}
